const ACTIONS = {
    JOIN_REQUEST: "join-request",
    JOIN_ACCEPTED: "join-accepted",
    USER_JOINED: "user-joined",
    USER_DISCONNECTED: "user-disconnected",
    SYNC_FILES: "sync-files",
    FILE_CREATED: "file-created",
    FILE_UPDATED: "file-updated",
    FILE_RENAMED: "file-renamed",
    FILE_DELETED: "file-deleted",
    USER_OFFLINE: "offline",
    USER_ONLINE: "online",
    SEND_MESSAGE: "send-message",
    RECEIVE_MESSAGE: "receive-message",
    TYPING_START: "typing-start",
    TYPING_PAUSE: "typing-pause",
    USERNAME_EXISTS: "username-exists",
    REQUEST_DRAWING: "request-drawing",
    SYNC_DRAWING: "sync-drawing",
    DRAWING_UPDATE: "drawing-update",
    // Room & auth actions
    CREATE_ROOM: "create-room",
    ROOM_CREATED: "room-created",
    JOIN_ROOM: "join-room",
    JOIN_ACCEPTED: "join-accepted",
    ROOM_CLOSED: "room-closed",
    END_ROOM: "end-room",
    SUBMIT_QUESTION: "submit-question",
    NEW_QUESTION: "new-question",
    SUBMIT_CODE: "submit-code",
    SUBMISSION_RECEIVED: "submission-received",
    REQUEST_ANALYSIS: "request-analysis",
    REQUEST_GENERATE: "request-generate",
    GENERATION_FAILED: "generation-failed",
    ANALYSIS_COMPLETE: "analysis-complete",
}

export default ACTIONS
